// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ||
      "postgresql://postgres:postgres@127.0.0.1:5433/dse12app_demo",
  },
};
